POST http://localhost:8000/api/register
Content-Type: application/json

{
    "login":"adam135",
    "password":"123"
}

###

POST http://localhost:8000/api/login 
Content-Type: application/json

{
    "login" :"adam",
    "password":"123"
}

###

GET http://localhost:8000/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTFiNjQ0ZDA3NmQzYjQ1MTExNGQ2NCIsImlhdCI6MTY1NTAyMzA0MX0.dzdc7sdgAviewUx5yXnb5iJDk3oIBJ10rpNIZWPXGy8

###

POST http://localhost:8000/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTFiNjQ0ZDA3NmQzYjQ1MTExNGQ2NCIsImlhdCI6MTY1NTAyMzA0MX0.dzdc7sdgAviewUx5yXnb5iJDk3oIBJ10rpNIZWPXGy8

{
    "title":"sometwerwereit3le",
    "message":"examplecontent34wer",
    "isurgent":true
}

### update note

POST http://localhost:8000/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTFiNjQ0ZDA3NmQzYjQ1MTExNGQ2NCIsImlhdCI6MTY1NTAyMzA0MX0.dzdc7sdgAviewUx5yXnb5iJDk3oIBJ10rpNIZWPXGy8

{
    "index":0,
    "propertyname":"isurgent",
    "value":false
}


###

DELETE  http://localhost:8000/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTFiNjQ0ZDA3NmQzYjQ1MTExNGQ2NCIsImlhdCI6MTY1NTI4ODIyMX0.V2ibxMK0dajjcBPfx-k_7L5CP-e_v90te6kwl98UvmQ

{
    "index": 2
}

###

GET  http://localhost:8000/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTFiNjQ0ZDA3NmQzYjQ1MTExNGQ2NCIsImlhdCI6MTY1NTAyMzA0MX0.dzdc7sdgAviewUx5yXnb5iJDk3oIBJ10rpNIZWPXGy8
